name: CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

env:
  CARGO_TERM_COLOR: always

jobs:

  ############################################################################
  # LINTERS
  #############################################################################

  lint:
    name: Lint
    # only run on branches
    if: format('refs/heads/{0}', github.event.repository.default_branch) != github.ref
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.sha }}  # lock to triggered commit (github.ref is dynamic)
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git target
          key: lint-cache-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
      - run: rustup update stable && rustup default stable
      - name: Run cargo install cargo-machete
        run: |
          if [ ! -f ~/.cargo/bin/cargo-machete ]; then
            cargo install cargo-machete
          fi
      - run: cargo machete
      - run: cargo fmt --all -- --check
      - run: cargo generate-lockfile --locked
      - run: cargo clippy --locked -- --deny warnings
      - run: cargo verify-project --locked
      - run: cargo doc --no-deps


  ############################################################################
  # TESTS
  #############################################################################

  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.sha }}  # lock to triggered commit (github.ref is dynamic)
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git target
          key: lint-cache-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
      - run: rustup update stable && rustup default stable
      - run: cargo build --verbose
      - run: cargo test --verbose

  coverage:
    name: Coverage
    # only run on branches
    if: format('refs/heads/{0}', github.event.repository.default_branch) != github.ref
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.sha }}  # lock to triggered commit (github.ref is dynamic)
      - uses: actions/cache@v4
        with:
          path: ~/.cargo/bin
          key: coverage-cache-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            coverage-cache-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
            coverage-cache-${{ runner.os }}-
      - run: rustup update stable && rustup default stable
      - name: Run cargo install cargo-tarpaulin
        run: |
          if [ ! -f ~/.cargo/bin/cargo-tarpaulin ]; then
            cargo install cargo-tarpaulin
          fi
      - run: cargo tarpaulin --fail-immediately --fail-under 20 --locked

  image-test-build:
    name: Image Test Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.sha }}  # lock to triggered commit (github.ref is dynamic)
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: false


  ############################################################################
  # TAG + RELEASE
  #############################################################################

  release-version:
    name: Release Version
    if: format('refs/heads/{0}', github.event.repository.default_branch) == github.ref
    needs: [
      lint,
      test,
      coverage,
      image-test-build
    ]
    runs-on: ubuntu-latest
    outputs:
      next-version: ${{ steps.next-version.outputs.version }}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.sha }}  # lock to triggered commit (github.ref is dynamic)
      # copied from tag-and-release
      - name: Determine next version
        uses: WIPACrepo/wipac-dev-next-version-action@v1.7
        id: next-version
        with:
          force-patch-if-no-commit-token: true
          ignore-paths: |
            **/README.md
            .github/**
            .gitignore

  tag-and-release:
    # only run on main/default branch
    needs: [ release-version ]
    if: format('refs/heads/{0}', github.event.repository.default_branch) == github.ref && needs.release-version.outputs.next-version != ''
    uses: WIPACrepo/wipac-dev-workflows/.github/workflows/tag-and-release.yml@v1.5
    permissions: # for GITHUB_TOKEN
      contents: write
    with:
      project-type: rust
      release-artifacts: |
        rpm
        binaries

  image-publish:
    if: format('refs/heads/{0}', github.event.repository.default_branch) == github.ref && needs.release-version.outputs.next-version != ''
    needs: [
      tag-and-release,
      release-version,
    ]
    uses: WIPACrepo/wipac-dev-workflows/.github/workflows/image-publish.yml@v1.20
    permissions: # for GITHUB_TOKEN
      packages: write
    with:
      image_namespace: wipacrepo
      image_name: data-warehouse-ingest
      mode: BUILD
      build_args: |
        VERSION=${{ needs.release-version.outputs.next-version }}
      extra_build_tag: ${{ needs.release-version.outputs.next-version }}
